server:
  port: 8081

spring:
  profiles:
    active: local

---
spring:
  profiles: local
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
    driver-class-name: org.h2.Driver
---
spring:
  profiles: mysql
  datasource:
    hikari:
      url: jdbc:mysql://localhost:3306/spring_batch
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver
