spring:
  datasource:
    url: jdbc:mysql://localhost:3306/good_choice
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      max-lifetime: 60000
      connection-timeout: 5000
      pool-name: Spring-HikariPool
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 16
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate:
      SQL: debug
      tool.hbm2ddl: debug
      type: trace
      stat: debug
      type.BasicTypeRegistry: warn
    org.springframework.jdbc: debug
